services:
  backend:
    build:
      context: ./
      args:
        - BUILD_ENV=production
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    volumes:
      - /root/learning-module:/var/www/html/vendor/qtvhao/learning-module/
      - /root/device-access-control/:/var/www/html/vendor/qtvhao/device-access-control/
      - ./storage-logs/:/var/www/html/storage/logs/
    command: [
      "bash", "-c",
      "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    ]
    depends_on:
      db:
        condition: service_healthy
  feature-test:
    build:
      context: ./
      args:
        - BUILD_ENV=testing
      dockerfile: ./dockerfiles/Dockerfile
    environment:
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    volumes:
      - /root/learning-module:/var/www/html/vendor/qtvhao/learning-module/
      - /root/device-access-control/:/var/www/html/vendor/qtvhao/device-access-control/
      - ./storage-logs/:/var/www/html/storage/logs/
    command: [
      "bash", "-c",
      "php artisan migrate --force && php artisan test"
    ]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: mysql_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
